CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(30)                                         NOT NULL,
    email VARCHAR(30)                                         NOT NULL
);
create unique index if not exists USER_EMAIL_UINDEX on USERS (email);

CREATE TABLE IF NOT EXISTS categories
(
    id   bigint generated by default as identity primary key not null,
    name VARCHAR(100)                                        NOT NULL
);
create unique index if not exists CATEGORIES_NAME_UINDEX on categories (name);

create table if not exists events
(
    id                 bigint generated always as identity primary key not null,
    annotation         varchar(200)                                    not null,
    category           bigint references categories,
    confirmedRequests  bigint,
    create_date        timestamp without time zone,
    description        varchar(255),
    event_date         timestamp without time zone                     not null,
    initiator          bigint references users,
    lat                float4                                          not null,
    lon                float4                                          not null,
    paid               boolean                                         not null,
    participantLimit   bigint,
    published_date     timestamp without time zone,
    request_moderation boolean,
    state              varchar(33),
    title              varchar(200)                                    not null,
    views              bigint default 0,
    CONSTRAINT pk_events PRIMARY KEY (id),
    FOREIGN KEY(category) REFERENCES categories(id) ON DELETE CASCADE,
    FOREIGN KEY(initiator) REFERENCES users(id) ON DELETE CASCADE
);
//create unique index if not exists EVENT_ID_UINDEX on EVENTS (id);


CREATE TABLE IF NOT EXISTS requests
(
    id       BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    user_id  BIGINT references users unique      NOT NULL,
    event_id BIGINT references events unique     NOT NULL,
    created  TIMESTAMP                           NOT NULL,
    status   VARCHAR(50)                         NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(255)                            NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);
//create unique index if not exists COMPILATION_ID_UINDEX on compilations (id);

CREATE TABLE IF NOT EXISTS compilations_events
(
    id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    compilation  BIGINT                                NOT NULL,
    event        BIGINT                                NOT NULL,
    FOREIGN KEY (compilation) REFERENCES compilations (id) ON DELETE CASCADE,
    FOREIGN KEY (event) REFERENCES events (id) ON DELETE CASCADE
);